# This file is used for building and pushing images
services:
  node:
    build:
      context: .
      dockerfile: operator.Dockerfile
    image: ghcr.io/h3lio5/incredible-array-summing-avs/node:latest
  nodeplugin:
    build:
      context: .
      dockerfile: plugin.Dockerfile
    image: ghcr.io/h3lio5/incredible-array-summing-avs/nodeplugin:latest
